SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS dc_demands (
  `type` varchar(15) NOT NULL,
  id_demand int(10) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  Subname varchar(255) NOT NULL,
  Association varchar(255) NOT NULL,
  Adress varchar(255) NOT NULL,
  Telephone varchar(10) NOT NULL,
  Domain varchar(150) NOT NULL,
  Mail varchar(100) NOT NULL,
  SIREN varchar(9) NOT NULL,
  Declaration varchar(25) NOT NULL,
  Validated tinyint(1) NOT NULL,
  `date` datetime NOT NULL,
  PRIMARY KEY (id_demand)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
